const ELEMENTS_DATA = [
    {
        "atomicNumber": 1,
        "symbol": "H",
        "name": "Hydrogen",
        "category": "diatomic nonmetal",
        "group": 1,
        "period": 1,
        "xpos": 1,
        "ypos": 1,
        "classification": "nonmetal",
        "commonIonCharge": "+1, -1",
        "electronegativity": 2.20,
        "valenceElectrons": 1,
        "summary": "Hydrogen is a chemical element with chemical symbol H and atomic number 1. With an atomic weight of 1.00794 u, hydrogen is the lightest element on the periodic table. Its monatomic form (H) is the most abundant chemical substance in the Universe, constituting roughly 75% of all baryonic mass.",
        "appearance": "colorless gas",
        "atomicMass": 1.008,
        "melt": 13.99,
        "boil": 20.271,
        "density": 0.08988,
        "phase": "Gas",
        "electronConfiguration": "1s1",
        "discoveredBy": "Henry Cavendish"
    },
    {
        "atomicNumber": 2,
        "symbol": "He",
        "name": "Helium",
        "category": "noble gas",
        "group": 18,
        "period": 1,
        "xpos": 18,
        "ypos": 1,
        "classification": "nonmetal",
        "commonIonCharge": null,
        "electronegativity": null,
        "valenceElectrons": 2,
        "summary": "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas that heads the noble gas group in the periodic table. Its boiling and melting points are the lowest among all the elements.",
        "appearance": "colorless gas, exhibiting a red-orange glow when placed in a high-voltage electric field",
        "atomicMass": 4.0026022,
        "melt": 0.95,
        "boil": 4.222,
        "density": 0.1786,
        "phase": "Gas",
        "electronConfiguration": "1s2",
        "discoveredBy": "Pierre Janssen"
    },
    {
        "atomicNumber": 3,
        "symbol": "Li",
        "name": "Lithium",
        "category": "alkali metal",
        "group": 1,
        "period": 2,
        "xpos": 1,
        "ypos": 2,
        "classification": "metal",
        "commonIonCharge": "+1",
        "electronegativity": 0.98,
        "valenceElectrons": 1,
        "summary": "Lithium is a chemical element with the symbol Li and atomic number 3. It is a soft, silver-white metal belonging to the alkali metal group of chemical elements. Under standard conditions it is the lightest metal and the least dense solid element.",
        "appearance": "silvery-white",
        "atomicMass": 6.94,
        "melt": 453.65,
        "boil": 1603,
        "density": 0.534,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s1",
        "discoveredBy": "Johan August Arfwedson"
    },
    {
        "atomicNumber": 4,
        "symbol": "Be",
        "name": "Beryllium",
        "category": "alkaline earth metal",
        "group": 2,
        "period": 2,
        "xpos": 2,
        "ypos": 2,
        "classification": "metal",
        "commonIonCharge": "+2",
        "electronegativity": 1.57,
        "valenceElectrons": 2,
        "summary": "Beryllium is a chemical element with symbol Be and atomic number 4. It is created through stellar nucleosynthesis and is a relatively rare element in the universe. It is a divalent element which occurs naturally only in combination with other elements in minerals.",
        "appearance": "white-gray metallic",
        "atomicMass": 9.01218315,
        "melt": 1560,
        "boil": 2742,
        "density": 1.85,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2",
        "discoveredBy": "Louis Nicolas Vauquelin"
    },
    {
        "atomicNumber": 5,
        "symbol": "B",
        "name": "Boron",
        "category": "metalloid",
        "group": 13,
        "period": 2,
        "xpos": 13,
        "ypos": 2,
        "classification": "metalloid",
        "commonIonCharge": "+3",
        "electronegativity": 2.04,
        "valenceElectrons": 3,
        "summary": "Boron is a metalloid chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in both the Solar system and the Earth's crust.",
        "appearance": "black-brown",
        "atomicMass": 10.81,
        "melt": 2349,
        "boil": 4200,
        "density": 2.08,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p1",
        "discoveredBy": "Joseph Louis Gay-Lussac"
    },
    {
        "atomicNumber": 6,
        "symbol": "C",
        "name": "Carbon",
        "category": "polyatomic nonmetal",
        "group": 14,
        "period": 2,
        "xpos": 14,
        "ypos": 2,
        "classification": "nonmetal",
        "commonIonCharge": "+4, -4",
        "electronegativity": 2.55,
        "valenceElectrons": 4,
        "summary": "Carbon is a chemical element with symbol C and atomic number 6. On the periodic table, it is the first of six elements in column 14, which have in common the composition of their outer electron shell. It is nonmetallic and tetravalent.",
        "appearance": null,
        "atomicMass": 12.011,
        "melt": null,
        "boil": null,
        "density": 1.821,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p2",
        "discoveredBy": "Ancient Egypt"
    },
    {
        "atomicNumber": 7,
        "symbol": "N",
        "name": "Nitrogen",
        "category": "diatomic nonmetal",
        "group": 15,
        "period": 2,
        "xpos": 15,
        "ypos": 2,
        "classification": "nonmetal",
        "commonIonCharge": "-3",
        "electronegativity": 3.04,
        "valenceElectrons": 5,
        "summary": "Nitrogen is a chemical element with symbol N and atomic number 7. It is the lightest pnictogen and at room temperature, it is a transparent, odorless diatomic gas. Nitrogen is a common element in the universe.",
        "appearance": "colorless gas, liquid or solid",
        "atomicMass": 14.007,
        "melt": 63.15,
        "boil": 77.355,
        "density": 1.251,
        "phase": "Gas",
        "electronConfiguration": "1s2 2s2 2p3",
        "discoveredBy": "Daniel Rutherford"
    },
    {
        "atomicNumber": 8,
        "symbol": "O",
        "name": "Oxygen",
        "category": "diatomic nonmetal",
        "group": 16,
        "period": 2,
        "xpos": 16,
        "ypos": 2,
        "classification": "nonmetal",
        "commonIonCharge": "-2",
        "electronegativity": 3.44,
        "valenceElectrons": 6,
        "summary": "Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the chalcogen group on the periodic table and is a highly reactive nonmetal and oxidizing agent that readily forms compounds with most elements.",
        "appearance": null,
        "atomicMass": 15.999,
        "melt": 54.36,
        "boil": 90.188,
        "density": 1.429,
        "phase": "Gas",
        "electronConfiguration": "1s2 2s2 2p4",
        "discoveredBy": "Carl Wilhelm Scheele"
    },
    {
        "atomicNumber": 9,
        "symbol": "F",
        "name": "Fluorine",
        "category": "diatomic nonmetal",
        "group": 17,
        "period": 2,
        "xpos": 17,
        "ypos": 2,
        "classification": "nonmetal",
        "commonIonCharge": "-1",
        "electronegativity": 3.98,
        "valenceElectrons": 7,
        "summary": "Fluorine is a chemical element with symbol F and atomic number 9. It is the lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions. As the most electronegative element, it is extremely reactive.",
        "appearance": null,
        "atomicMass": 18.998403163,
        "melt": 53.48,
        "boil": 85.03,
        "density": 1.696,
        "phase": "Gas",
        "electronConfiguration": "1s2 2s2 2p5",
        "discoveredBy": "Andre-Marie Ampere"
    },
    {
        "atomicNumber": 10,
        "symbol": "Ne",
        "name": "Neon",
        "category": "noble gas",
        "group": 18,
        "period": 2,
        "xpos": 18,
        "ypos": 2,
        "classification": "nonmetal",
        "commonIonCharge": null,
        "electronegativity": null,
        "valenceElectrons": 8,
        "summary": "Neon is a chemical element with symbol Ne and atomic number 10. It is in group 18 of the periodic table. Neon is a colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air.",
        "appearance": "colorless gas exhibiting an orange-red glow when placed in a high voltage electric field",
        "atomicMass": 20.1797,
        "melt": 24.56,
        "boil": 27.104,
        "density": 0.9002,
        "phase": "Gas",
        "electronConfiguration": "1s2 2s2 2p6",
        "discoveredBy": "Morris Travers"
    },
    {
        "atomicNumber": 11,
        "symbol": "Na",
        "name": "Sodium",
        "category": "alkali metal",
        "group": 1,
        "period": 3,
        "xpos": 1,
        "ypos": 3,
        "classification": "metal",
        "commonIonCharge": "+1",
        "electronegativity": 0.93,
        "valenceElectrons": 1,
        "summary": "Sodium is a chemical element with symbol Na and atomic number 11. It is a soft, silver-white, highly reactive metal. In the Periodic table it is in column 1 (alkali metals).",
        "appearance": "silvery white metallic",
        "atomicMass": 22.98976928,
        "melt": 370.944,
        "boil": 1156.09,
        "density": 0.968,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s1",
        "discoveredBy": "Humphry Davy"
    },
    {
        "atomicNumber": 12,
        "symbol": "Mg",
        "name": "Magnesium",
        "category": "alkaline earth metal",
        "group": 2,
        "period": 3,
        "xpos": 2,
        "ypos": 3,
        "classification": "metal",
        "commonIonCharge": "+2",
        "electronegativity": 1.31,
        "valenceElectrons": 2,
        "summary": "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column of the periodic table.",
        "appearance": "shiny grey solid",
        "atomicMass": 24.305,
        "melt": 923,
        "boil": 1363,
        "density": 1.738,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2",
        "discoveredBy": "Joseph Black"
    },
    {
        "atomicNumber": 13,
        "symbol": "Al",
        "name": "Aluminium",
        "category": "post-transition metal",
        "group": 13,
        "period": 3,
        "xpos": 13,
        "ypos": 3,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.61,
        "valenceElectrons": 3,
        "summary": "Aluminium is a chemical element in the boron group with symbol Al and atomic number 13. It is a silvery-white, soft, nonmagnetic, ductile metal. Aluminium is the third most abundant element in the Earth's crust.",
        "appearance": "silvery gray metallic",
        "atomicMass": 26.9815385,
        "melt": 933.47,
        "boil": 2743,
        "density": 2.7,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p1",
        "discoveredBy": null
    },
    {
        "atomicNumber": 14,
        "symbol": "Si",
        "name": "Silicon",
        "category": "metalloid",
        "group": 14,
        "period": 3,
        "xpos": 14,
        "ypos": 3,
        "classification": "metalloid",
        "commonIonCharge": "+4, -4",
        "electronegativity": 1.90,
        "valenceElectrons": 4,
        "summary": "Silicon is a chemical element with symbol Si and atomic number 14. It is a tetravalent metalloid, more reactive than germanium, the metalloid directly below it in the table.",
        "appearance": "crystalline, reflective with bluish-tinged faces",
        "atomicMass": 28.085,
        "melt": 1687,
        "boil": 3538,
        "density": 2.329,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p2",
        "discoveredBy": "Jons Jacob Berzelius"
    },
    {
        "atomicNumber": 15,
        "symbol": "P",
        "name": "Phosphorus",
        "category": "polyatomic nonmetal",
        "group": 15,
        "period": 3,
        "xpos": 15,
        "ypos": 3,
        "classification": "nonmetal",
        "commonIonCharge": "-3, +5",
        "electronegativity": 2.19,
        "valenceElectrons": 5,
        "summary": "Phosphorus is a chemical element with symbol P and atomic number 15. As an element, phosphorus exists in two major forms—white phosphorus and red phosphorus. It is highly reactive.",
        "appearance": "colourless, waxy white, yellow, scarlet, red, violet, black",
        "atomicMass": 30.973762,
        "melt": 317.3,
        "boil": 553.7,
        "density": 1.823,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p3",
        "discoveredBy": "Hennig Brand"
    },
    {
        "atomicNumber": 16,
        "symbol": "S",
        "name": "Sulfur",
        "category": "polyatomic nonmetal",
        "group": 16,
        "period": 3,
        "xpos": 16,
        "ypos": 3,
        "classification": "nonmetal",
        "commonIonCharge": "-2",
        "electronegativity": 2.58,
        "valenceElectrons": 6,
        "summary": "Sulfur is a chemical element with symbol S and atomic number 16. It is abundant, multivalent, and nonmetallic. Under normal conditions, sulfur atoms form cyclic octatomic molecules with chemical formula S8.",
        "appearance": "lemon yellow sinite",
        "atomicMass": 32.06,
        "melt": 388.36,
        "boil": 717.8,
        "density": 1.96,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p4",
        "discoveredBy": "Ancient China"
    },
    {
        "atomicNumber": 17,
        "symbol": "Cl",
        "name": "Chlorine",
        "category": "diatomic nonmetal",
        "group": 17,
        "period": 3,
        "xpos": 17,
        "ypos": 3,
        "classification": "nonmetal",
        "commonIonCharge": "-1",
        "electronegativity": 3.16,
        "valenceElectrons": 7,
        "summary": "Chlorine is a chemical element with symbol Cl and atomic number 17. It is a yellow-green gas at room temperature. It is an extremely reactive element and a strong oxidising agent.",
        "appearance": "pale yellow-green gas",
        "atomicMass": 35.45,
        "melt": 171.6,
        "boil": 239.11,
        "density": 3.2,
        "phase": "Gas",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p5",
        "discoveredBy": "Carl Wilhelm Scheele"
    },
    {
        "atomicNumber": 18,
        "symbol": "Ar",
        "name": "Argon",
        "category": "noble gas",
        "group": 18,
        "period": 3,
        "xpos": 18,
        "ypos": 3,
        "classification": "nonmetal",
        "commonIonCharge": null,
        "electronegativity": null,
        "valenceElectrons": 8,
        "summary": "Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas. Argon is the third most common gas in the Earth's atmosphere.",
        "appearance": "colorless gas exhibiting a lilac/violet glow when placed in a high voltage electric field",
        "atomicMass": 39.948,
        "melt": 83.81,
        "boil": 87.302,
        "density": 1.784,
        "phase": "Gas",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6",
        "discoveredBy": "Lord Rayleigh"
    },
    {
        "atomicNumber": 19,
        "symbol": "K",
        "name": "Potassium",
        "category": "alkali metal",
        "group": 1,
        "period": 4,
        "xpos": 1,
        "ypos": 4,
        "classification": "metal",
        "commonIonCharge": "+1",
        "electronegativity": 0.82,
        "valenceElectrons": 1,
        "summary": "Potassium is a chemical element with symbol K and atomic number 19. It was first isolated from potash. Potassium is a silvery-white metal that is soft enough to be cut with a knife.",
        "appearance": "silvery gray",
        "atomicMass": 39.0983,
        "melt": 336.7,
        "boil": 1032,
        "density": 0.89,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s1",
        "discoveredBy": "Humphry Davy"
    },
    {
        "atomicNumber": 20,
        "symbol": "Ca",
        "name": "Calcium",
        "category": "alkaline earth metal",
        "group": 2,
        "period": 4,
        "xpos": 2,
        "ypos": 4,
        "classification": "metal",
        "commonIonCharge": "+2",
        "electronegativity": 1.00,
        "valenceElectrons": 2,
        "summary": "Calcium is a chemical element with symbol Ca and atomic number 20. Calcium is a soft gray alkaline earth metal, fifth-most-abundant element by mass in the Earth's crust.",
        "appearance": null,
        "atomicMass": 40.078,
        "melt": 1115,
        "boil": 1757,
        "density": 1.55,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2",
        "discoveredBy": "Humphry Davy"
    },
    {
        "atomicNumber": 21,
        "symbol": "Sc",
        "name": "Scandium",
        "category": "transition metal",
        "group": 3,
        "period": 4,
        "xpos": 3,
        "ypos": 4,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.36,
        "valenceElectrons": 3,
        "summary": "Scandium is a chemical element with symbol Sc and atomic number 21. A silvery-white metallic d-block element, it has historically been sometimes classified as a rare earth element.",
        "appearance": "silvery white",
        "atomicMass": 44.955908,
        "melt": 1814,
        "boil": 3109,
        "density": 2.985,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d1",
        "discoveredBy": "Lars Fredrik Nilson"
    },
    {
        "atomicNumber": 22,
        "symbol": "Ti",
        "name": "Titanium",
        "category": "transition metal",
        "group": 4,
        "period": 4,
        "xpos": 4,
        "ypos": 4,
        "classification": "metal",
        "commonIonCharge": "+4, +3",
        "electronegativity": 1.54,
        "valenceElectrons": 4,
        "summary": "Titanium is a chemical element with symbol Ti and atomic number 22. It is a lustrous transition metal with a silver color, low density and high strength.",
        "appearance": "silvery grey-white metallic",
        "atomicMass": 47.867,
        "melt": 1941,
        "boil": 3560,
        "density": 4.506,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d2",
        "discoveredBy": "William Gregor"
    },
    {
        "atomicNumber": 23,
        "symbol": "V",
        "name": "Vanadium",
        "category": "transition metal",
        "group": 5,
        "period": 4,
        "xpos": 5,
        "ypos": 4,
        "classification": "metal",
        "commonIonCharge": "+5, +4, +3, +2",
        "electronegativity": 1.63,
        "valenceElectrons": 5,
        "summary": "Vanadium is a chemical element with symbol V and atomic number 23. It is a hard, silvery grey, ductile and malleable transition metal.",
        "appearance": "blue-silver-grey metal",
        "atomicMass": 50.9415,
        "melt": 2183,
        "boil": 3680,
        "density": 6.11,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d3",
        "discoveredBy": "Andres Manuel del Rio"
    },
    {
        "atomicNumber": 24,
        "symbol": "Cr",
        "name": "Chromium",
        "category": "transition metal",
        "group": 6,
        "period": 4,
        "xpos": 6,
        "ypos": 4,
        "classification": "metal",
        "commonIonCharge": "+3, +6",
        "electronegativity": 1.66,
        "valenceElectrons": 6,
        "summary": "Chromium is a chemical element with symbol Cr and atomic number 24. It is the first element in Group 6. It is a steely-grey, lustrous, hard and brittle metal.",
        "appearance": "silvery metallic",
        "atomicMass": 51.9961,
        "melt": 2180,
        "boil": 2944,
        "density": 7.19,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s1 3d5",
        "discoveredBy": "Louis Nicolas Vauquelin"
    },
    {
        "atomicNumber": 25,
        "symbol": "Mn",
        "name": "Manganese",
        "category": "transition metal",
        "group": 7,
        "period": 4,
        "xpos": 7,
        "ypos": 4,
        "classification": "metal",
        "commonIonCharge": "+2, +4, +7",
        "electronegativity": 1.55,
        "valenceElectrons": 7,
        "summary": "Manganese is a chemical element with symbol Mn and atomic number 25. It is not found as a free element in nature; it is often found in combination with iron.",
        "appearance": "silvery metallic",
        "atomicMass": 54.938044,
        "melt": 1519,
        "boil": 2334,
        "density": 7.21,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d5",
        "discoveredBy": "Torbern Olof Bergman"
    },
    {
        "atomicNumber": 26,
        "symbol": "Fe",
        "name": "Iron",
        "category": "transition metal",
        "group": 8,
        "period": 4,
        "xpos": 8,
        "ypos": 4,
        "classification": "metal",
        "commonIonCharge": "+2, +3",
        "electronegativity": 1.83,
        "valenceElectrons": 8,
        "summary": "Iron is a chemical element with symbol Fe and atomic number 26. It is a metal in the first transition series. It is by mass the most common element on Earth.",
        "appearance": "lustrous metallic with a grayish tinge",
        "atomicMass": 55.845,
        "melt": 1811,
        "boil": 3134,
        "density": 7.874,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d6",
        "discoveredBy": "Ancient"
    },
    {
        "atomicNumber": 27,
        "symbol": "Co",
        "name": "Cobalt",
        "category": "transition metal",
        "group": 9,
        "period": 4,
        "xpos": 9,
        "ypos": 4,
        "classification": "metal",
        "commonIonCharge": "+2, +3",
        "electronegativity": 1.88,
        "valenceElectrons": 9,
        "summary": "Cobalt is a chemical element with symbol Co and atomic number 27. Like nickel, cobalt is found in the Earth's crust only in chemically combined form.",
        "appearance": "hard lustrous gray metal",
        "atomicMass": 58.933194,
        "melt": 1768,
        "boil": 3200,
        "density": 8.9,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d7",
        "discoveredBy": "Georg Brandt"
    },
    {
        "atomicNumber": 28,
        "symbol": "Ni",
        "name": "Nickel",
        "category": "transition metal",
        "group": 10,
        "period": 4,
        "xpos": 10,
        "ypos": 4,
        "classification": "metal",
        "commonIonCharge": "+2",
        "electronegativity": 1.91,
        "valenceElectrons": 10,
        "summary": "Nickel is a chemical element with symbol Ni and atomic number 28. It is a silvery-white lustrous metal with a slight golden tinge.",
        "appearance": "lustrous, metallic, and silver with a gold tinge",
        "atomicMass": 58.6934,
        "melt": 1728,
        "boil": 3003,
        "density": 8.908,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d8",
        "discoveredBy": "Axel Fredrik Cronstedt"
    },
    {
        "atomicNumber": 29,
        "symbol": "Cu",
        "name": "Copper",
        "category": "transition metal",
        "group": 11,
        "period": 4,
        "xpos": 11,
        "ypos": 4,
        "classification": "metal",
        "commonIonCharge": "+1, +2",
        "electronegativity": 1.90,
        "valenceElectrons": 11,
        "summary": "Copper is a chemical element with symbol Cu and atomic number 29. It is a soft, malleable and ductile metal with very high thermal and electrical conductivity.",
        "appearance": "red-orange metallic luster",
        "atomicMass": 63.546,
        "melt": 1357.77,
        "boil": 2835,
        "density": 8.96,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s1 3d10",
        "discoveredBy": "Ancient"
    },
    {
        "atomicNumber": 30,
        "symbol": "Zn",
        "name": "Zinc",
        "category": "transition metal",
        "group": 12,
        "period": 4,
        "xpos": 12,
        "ypos": 4,
        "classification": "metal",
        "commonIonCharge": "+2",
        "electronegativity": 1.65,
        "valenceElectrons": 2,
        "summary": "Zinc is a chemical element with symbol Zn and atomic number 30. It is the first element of group 12 of the periodic table.",
        "appearance": "silver-gray",
        "atomicMass": 65.38,
        "melt": 692.68,
        "boil": 1180,
        "density": 7.14,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10",
        "discoveredBy": "India"
    },
    {
        "atomicNumber": 31,
        "symbol": "Ga",
        "name": "Gallium",
        "category": "post-transition metal",
        "group": 13,
        "period": 4,
        "xpos": 13,
        "ypos": 4,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.81,
        "valenceElectrons": 3,
        "summary": "Gallium is a chemical element with symbol Ga and atomic number 31. Elemental gallium does not occur in free form in nature.",
        "appearance": "silver-white",
        "atomicMass": 69.723,
        "melt": 302.9146,
        "boil": 2673,
        "density": 5.91,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p1",
        "discoveredBy": "Lecoq de Boisbaudran"
    },
    {
        "atomicNumber": 32,
        "symbol": "Ge",
        "name": "Germanium",
        "category": "metalloid",
        "group": 14,
        "period": 4,
        "xpos": 14,
        "ypos": 4,
        "classification": "metalloid",
        "commonIonCharge": "+4, +2",
        "electronegativity": 2.01,
        "valenceElectrons": 4,
        "summary": "Germanium is a chemical element with symbol Ge and atomic number 32. It is a lustrous, hard, grayish-white metalloid in the carbon group.",
        "appearance": "grayish-white",
        "atomicMass": 72.63,
        "melt": 1211.4,
        "boil": 3106,
        "density": 5.323,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p2",
        "discoveredBy": "Clemens Winkler"
    },
    {
        "atomicNumber": 33,
        "symbol": "As",
        "name": "Arsenic",
        "category": "metalloid",
        "group": 15,
        "period": 4,
        "xpos": 15,
        "ypos": 4,
        "classification": "metalloid",
        "commonIonCharge": "-3, +3, +5",
        "electronegativity": 2.18,
        "valenceElectrons": 5,
        "summary": "Arsenic is a chemical element with symbol As and atomic number 33. Arsenic occurs in many minerals, usually in conjunction with sulfur and metals.",
        "appearance": "metallic grey",
        "atomicMass": 74.921595,
        "melt": 1090,
        "boil": 887,
        "density": 5.727,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p3",
        "discoveredBy": "Bronze Age"
    },
    {
        "atomicNumber": 34,
        "symbol": "Se",
        "name": "Selenium",
        "category": "polyatomic nonmetal",
        "group": 16,
        "period": 4,
        "xpos": 16,
        "ypos": 4,
        "classification": "nonmetal",
        "commonIonCharge": "-2",
        "electronegativity": 2.55,
        "valenceElectrons": 6,
        "summary": "Selenium is a chemical element with symbol Se and atomic number 34. It is a nonmetal with properties that are intermediate between those of its periodic table column-adjacent chalcogen elements sulfur and tellurium.",
        "appearance": "black, red, and gray allotropes",
        "atomicMass": 78.971,
        "melt": 494,
        "boil": 958,
        "density": 4.81,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p4",
        "discoveredBy": "Jons Jacob Berzelius"
    },
    {
        "atomicNumber": 35,
        "symbol": "Br",
        "name": "Bromine",
        "category": "diatomic nonmetal",
        "group": 17,
        "period": 4,
        "xpos": 17,
        "ypos": 4,
        "classification": "nonmetal",
        "commonIonCharge": "-1",
        "electronegativity": 2.96,
        "valenceElectrons": 7,
        "summary": "Bromine is a chemical element with symbol Br and atomic number 35. It is a fuming red-brown liquid at room temperature that evaporates readily to form a similarly coloured gas.",
        "appearance": "red-brown",
        "atomicMass": 79.904,
        "melt": 265.8,
        "boil": 332,
        "density": 3.1028,
        "phase": "Liquid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p5",
        "discoveredBy": "Antoine Jerome Balard"
    },
    {
        "atomicNumber": 36,
        "symbol": "Kr",
        "name": "Krypton",
        "category": "noble gas",
        "group": 18,
        "period": 4,
        "xpos": 18,
        "ypos": 4,
        "classification": "nonmetal",
        "commonIonCharge": null,
        "electronegativity": 3.00,
        "valenceElectrons": 8,
        "summary": "Krypton is a chemical element with symbol Kr and atomic number 36. It is a member of group 18 (noble gases) elements.",
        "appearance": "colorless gas, exhibiting a whitish glow in a high electric field",
        "atomicMass": 83.798,
        "melt": 115.78,
        "boil": 119.93,
        "density": 3.749,
        "phase": "Gas",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6",
        "discoveredBy": "William Ramsay"
    },
    {
        "atomicNumber": 37,
        "symbol": "Rb",
        "name": "Rubidium",
        "category": "alkali metal",
        "group": 1,
        "period": 5,
        "xpos": 1,
        "ypos": 5,
        "classification": "metal",
        "commonIonCharge": "+1",
        "electronegativity": 0.82,
        "valenceElectrons": 1,
        "summary": "Rubidium is a chemical element with symbol Rb and atomic number 37. Rubidium is a soft, silvery-white metallic element of the alkali metal group.",
        "appearance": "grey white",
        "atomicMass": 85.4678,
        "melt": 312.45,
        "boil": 961,
        "density": 1.532,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1",
        "discoveredBy": "Robert Bunsen"
    },
    {
        "atomicNumber": 38,
        "symbol": "Sr",
        "name": "Strontium",
        "category": "alkaline earth metal",
        "group": 2,
        "period": 5,
        "xpos": 2,
        "ypos": 5,
        "classification": "metal",
        "commonIonCharge": "+2",
        "electronegativity": 0.95,
        "valenceElectrons": 2,
        "summary": "Strontium is a chemical element with symbol Sr and atomic number 38. An alkaline earth metal, strontium is a soft silver-white or yellowish metallic element.",
        "appearance": null,
        "atomicMass": 87.62,
        "melt": 1050,
        "boil": 1650,
        "density": 2.64,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2",
        "discoveredBy": "William Cruickshank"
    },
    {
        "atomicNumber": 39,
        "symbol": "Y",
        "name": "Yttrium",
        "category": "transition metal",
        "group": 3,
        "period": 5,
        "xpos": 3,
        "ypos": 5,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.22,
        "valenceElectrons": 3,
        "summary": "Yttrium is a chemical element with symbol Y and atomic number 39. It is a silvery-metallic transition metal chemically similar to the lanthanides.",
        "appearance": "silvery white",
        "atomicMass": 88.90584,
        "melt": 1799,
        "boil": 3203,
        "density": 4.472,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d1",
        "discoveredBy": "Johan Gadolin"
    },
    {
        "atomicNumber": 40,
        "symbol": "Zr",
        "name": "Zirconium",
        "category": "transition metal",
        "group": 4,
        "period": 5,
        "xpos": 4,
        "ypos": 5,
        "classification": "metal",
        "commonIonCharge": "+4",
        "electronegativity": 1.33,
        "valenceElectrons": 4,
        "summary": "Zirconium is a chemical element with symbol Zr and atomic number 40. The name zirconium is taken from the name of the mineral zircon.",
        "appearance": "silvery white",
        "atomicMass": 91.224,
        "melt": 2128,
        "boil": 4650,
        "density": 6.52,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d2",
        "discoveredBy": "Martin Heinrich Klaproth"
    },
    {
        "atomicNumber": 41,
        "symbol": "Nb",
        "name": "Niobium",
        "category": "transition metal",
        "group": 5,
        "period": 5,
        "xpos": 5,
        "ypos": 5,
        "classification": "metal",
        "commonIonCharge": "+5, +3",
        "electronegativity": 1.6,
        "valenceElectrons": 5,
        "summary": "Niobium is a chemical element with symbol Nb and atomic number 41. It is a soft, grey, ductile transition metal, which is often found in the pyrochlore mineral.",
        "appearance": "gray metallic, bluish when oxidized",
        "atomicMass": 92.90637,
        "melt": 2750,
        "boil": 5017,
        "density": 8.57,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1 4d4",
        "discoveredBy": "Charles Hatchett"
    },
    {
        "atomicNumber": 42,
        "symbol": "Mo",
        "name": "Molybdenum",
        "category": "transition metal",
        "group": 6,
        "period": 5,
        "xpos": 6,
        "ypos": 5,
        "classification": "metal",
        "commonIonCharge": "+6, +4",
        "electronegativity": 2.16,
        "valenceElectrons": 6,
        "summary": "Molybdenum is a chemical element with symbol Mo and atomic number 42. The name is from Neo-Latin Molybdaenum.",
        "appearance": "gray metallic",
        "atomicMass": 95.95,
        "melt": 2896,
        "boil": 4912,
        "density": 10.28,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1 4d5",
        "discoveredBy": "Carl Wilhelm Scheele"
    },
    {
        "atomicNumber": 43,
        "symbol": "Tc",
        "name": "Technetium",
        "category": "transition metal",
        "group": 7,
        "period": 5,
        "xpos": 7,
        "ypos": 5,
        "classification": "metal",
        "commonIonCharge": "+7, +4",
        "electronegativity": 1.9,
        "valenceElectrons": 7,
        "summary": "Technetium is a chemical element with symbol Tc and atomic number 43. It is the element with the lowest atomic number in the periodic table that has no stable isotopes.",
        "appearance": "shiny gray metal",
        "atomicMass": 98,
        "melt": 2430,
        "boil": 4538,
        "density": 11,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d5",
        "discoveredBy": "Emilio Segre"
    },
    {
        "atomicNumber": 44,
        "symbol": "Ru",
        "name": "Ruthenium",
        "category": "transition metal",
        "group": 8,
        "period": 5,
        "xpos": 8,
        "ypos": 5,
        "classification": "metal",
        "commonIonCharge": "+3, +4",
        "electronegativity": 2.2,
        "valenceElectrons": 8,
        "summary": "Ruthenium is a chemical element with symbol Ru and atomic number 44. It is a rare transition metal belonging to the platinum group of the periodic table.",
        "appearance": "silvery white metallic",
        "atomicMass": 101.07,
        "melt": 2607,
        "boil": 4423,
        "density": 12.45,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1 4d7",
        "discoveredBy": "Karl Ernst Claus"
    },
    {
        "atomicNumber": 45,
        "symbol": "Rh",
        "name": "Rhodium",
        "category": "transition metal",
        "group": 9,
        "period": 5,
        "xpos": 9,
        "ypos": 5,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 2.28,
        "valenceElectrons": 9,
        "summary": "Rhodium is a chemical element with symbol Rh and atomic number 45. It is a rare, silvery-white, hard, and chemically inert transition metal.",
        "appearance": "silvery white metallic",
        "atomicMass": 102.9055,
        "melt": 2237,
        "boil": 3968,
        "density": 12.41,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1 4d8",
        "discoveredBy": "William Hyde Wollaston"
    },
    {
        "atomicNumber": 46,
        "symbol": "Pd",
        "name": "Palladium",
        "category": "transition metal",
        "group": 10,
        "period": 5,
        "xpos": 10,
        "ypos": 5,
        "classification": "metal",
        "commonIonCharge": "+2, +4",
        "electronegativity": 2.20,
        "valenceElectrons": 10,
        "summary": "Palladium is a chemical element with symbol Pd and atomic number 46. It is a rare and lustrous silvery-white metal discovered in 1803.",
        "appearance": "silvery white",
        "atomicMass": 106.42,
        "melt": 1828.05,
        "boil": 3236,
        "density": 12.023,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 4d10",
        "discoveredBy": "William Hyde Wollaston"
    },
    {
        "atomicNumber": 47,
        "symbol": "Ag",
        "name": "Silver",
        "category": "transition metal",
        "group": 11,
        "period": 5,
        "xpos": 11,
        "ypos": 5,
        "classification": "metal",
        "commonIonCharge": "+1",
        "electronegativity": 1.93,
        "valenceElectrons": 11,
        "summary": "Silver is a chemical element with symbol Ag and atomic number 47. A soft, white, lustrous transition metal, it possesses the highest electrical conductivity of any element.",
        "appearance": "lustrous white metal",
        "atomicMass": 107.8682,
        "melt": 1234.93,
        "boil": 2435,
        "density": 10.49,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1 4d10",
        "discoveredBy": "Ancient"
    },
    {
        "atomicNumber": 48,
        "symbol": "Cd",
        "name": "Cadmium",
        "category": "transition metal",
        "group": 12,
        "period": 5,
        "xpos": 12,
        "ypos": 5,
        "classification": "metal",
        "commonIonCharge": "+2",
        "electronegativity": 1.69,
        "valenceElectrons": 2,
        "summary": "Cadmium is a chemical element with symbol Cd and atomic number 48. This soft, bluish-white metal is chemically similar to zinc and mercury.",
        "appearance": "silvery bluish-gray metallic",
        "atomicMass": 112.414,
        "melt": 594.22,
        "boil": 1040,
        "density": 8.65,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10",
        "discoveredBy": "Karl Samuel Leberecht Hermann"
    },
    {
        "atomicNumber": 49,
        "symbol": "In",
        "name": "Indium",
        "category": "post-transition metal",
        "group": 13,
        "period": 5,
        "xpos": 13,
        "ypos": 5,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.78,
        "valenceElectrons": 3,
        "summary": "Indium is a chemical element with symbol In and atomic number 49. It is a post-transition metallic element that is rare in Earth's crust.",
        "appearance": "silvery lustrous gray",
        "atomicMass": 114.818,
        "melt": 429.7485,
        "boil": 2345,
        "density": 7.31,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p1",
        "discoveredBy": "Ferdinand Reich"
    },
    {
        "atomicNumber": 50,
        "symbol": "Sn",
        "name": "Tin",
        "category": "post-transition metal",
        "group": 14,
        "period": 5,
        "xpos": 14,
        "ypos": 5,
        "classification": "metal",
        "commonIonCharge": "+2, +4",
        "electronegativity": 1.96,
        "valenceElectrons": 4,
        "summary": "Tin is a chemical element with the symbol Sn and atomic number 50. It is a main group metal in group 14 of the periodic table.",
        "appearance": "silvery-white or gray",
        "atomicMass": 118.71,
        "melt": 505.08,
        "boil": 2875,
        "density": 7.365,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p2",
        "discoveredBy": "Ancient"
    },
    {
        "atomicNumber": 51,
        "symbol": "Sb",
        "name": "Antimony",
        "category": "metalloid",
        "group": 15,
        "period": 5,
        "xpos": 15,
        "ypos": 5,
        "classification": "metalloid",
        "commonIonCharge": "-3, +3, +5",
        "electronegativity": 2.05,
        "valenceElectrons": 5,
        "summary": "Antimony is a chemical element with symbol Sb and atomic number 51. A lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite.",
        "appearance": "silvery lustrous gray",
        "atomicMass": 121.76,
        "melt": 903.78,
        "boil": 1908,
        "density": 6.697,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p3",
        "discoveredBy": "Ancient"
    },
    {
        "atomicNumber": 52,
        "symbol": "Te",
        "name": "Tellurium",
        "category": "metalloid",
        "group": 16,
        "period": 5,
        "xpos": 16,
        "ypos": 5,
        "classification": "metalloid",
        "commonIonCharge": "-2, +4, +6",
        "electronegativity": 2.1,
        "valenceElectrons": 6,
        "summary": "Tellurium is a chemical element with symbol Te and atomic number 52. It is a brittle, mildly toxic, rare, silver-white metalloid.",
        "appearance": null,
        "atomicMass": 127.6,
        "melt": 722.66,
        "boil": 1261,
        "density": 6.24,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p4",
        "discoveredBy": "Franz-Joseph Muller von Reichenstein"
    },
    {
        "atomicNumber": 53,
        "symbol": "I",
        "name": "Iodine",
        "category": "diatomic nonmetal",
        "group": 17,
        "period": 5,
        "xpos": 17,
        "ypos": 5,
        "classification": "nonmetal",
        "commonIonCharge": "-1",
        "electronegativity": 2.66,
        "valenceElectrons": 7,
        "summary": "Iodine is a chemical element with symbol I and atomic number 53. The name is from Greek ioeides, meaning violet or purple.",
        "appearance": "lustrous metallic gray, violet as a gas",
        "atomicMass": 126.90447,
        "melt": 386.85,
        "boil": 457.4,
        "density": 4.933,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p5",
        "discoveredBy": "Bernard Courtois"
    },
    {
        "atomicNumber": 54,
        "symbol": "Xe",
        "name": "Xenon",
        "category": "noble gas",
        "group": 18,
        "period": 5,
        "xpos": 18,
        "ypos": 5,
        "classification": "nonmetal",
        "commonIonCharge": null,
        "electronegativity": 2.6,
        "valenceElectrons": 8,
        "summary": "Xenon is a chemical element with symbol Xe and atomic number 54. It is a colorless, dense, odorless noble gas.",
        "appearance": "colorless gas, exhibiting a blue glow when placed in a high voltage electric field",
        "atomicMass": 131.293,
        "melt": 161.4,
        "boil": 165.051,
        "density": 5.894,
        "phase": "Gas",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6",
        "discoveredBy": "William Ramsay"
    },
    {
        "atomicNumber": 55,
        "symbol": "Cs",
        "name": "Cesium",
        "category": "alkali metal",
        "group": 1,
        "period": 6,
        "xpos": 1,
        "ypos": 6,
        "classification": "metal",
        "commonIonCharge": "+1",
        "electronegativity": 0.79,
        "valenceElectrons": 1,
        "summary": "Caesium or cesium is a chemical element with symbol Cs and atomic number 55. It is a soft, silvery-gold alkali metal with a melting point of 28C.",
        "appearance": "silvery gold",
        "atomicMass": 132.90545196,
        "melt": 301.7,
        "boil": 944,
        "density": 1.93,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s1",
        "discoveredBy": "Robert Bunsen"
    },
    {
        "atomicNumber": 56,
        "symbol": "Ba",
        "name": "Barium",
        "category": "alkaline earth metal",
        "group": 2,
        "period": 6,
        "xpos": 2,
        "ypos": 6,
        "classification": "metal",
        "commonIonCharge": "+2",
        "electronegativity": 0.89,
        "valenceElectrons": 2,
        "summary": "Barium is a chemical element with symbol Ba and atomic number 56. It is the fifth element in Group 2, a soft silvery metallic alkaline earth metal.",
        "appearance": null,
        "atomicMass": 137.327,
        "melt": 1000,
        "boil": 2118,
        "density": 3.51,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2",
        "discoveredBy": "Carl Wilhelm Scheele"
    },
    {
        "atomicNumber": 57,
        "symbol": "La",
        "name": "Lanthanum",
        "category": "lanthanide",
        "group": 3,
        "period": 6,
        "xpos": 3,
        "ypos": 9,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.1,
        "valenceElectrons": 3,
        "summary": "Lanthanum is a soft, ductile, silvery-white metallic chemical element with symbol La and atomic number 57.",
        "appearance": "silvery white",
        "atomicMass": 138.90547,
        "melt": 1193,
        "boil": 3737,
        "density": 6.162,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 5d1",
        "discoveredBy": "Carl Gustaf Mosander"
    },
    {
        "atomicNumber": 58,
        "symbol": "Ce",
        "name": "Cerium",
        "category": "lanthanide",
        "group": 3,
        "period": 6,
        "xpos": 4,
        "ypos": 9,
        "classification": "metal",
        "commonIonCharge": "+3, +4",
        "electronegativity": 1.12,
        "valenceElectrons": 4,
        "summary": "Cerium is a chemical element with symbol Ce and atomic number 58. It is a soft, silvery, ductile metal which easily oxidizes in air.",
        "appearance": "silvery white",
        "atomicMass": 140.116,
        "melt": 1068,
        "boil": 3716,
        "density": 6.77,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f1 5d1",
        "discoveredBy": "Martin Heinrich Klaproth"
    },
    {
        "atomicNumber": 59,
        "symbol": "Pr",
        "name": "Praseodymium",
        "category": "lanthanide",
        "group": 3,
        "period": 6,
        "xpos": 5,
        "ypos": 9,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.13,
        "valenceElectrons": 5,
        "summary": "Praseodymium is a chemical element with symbol Pr and atomic number 59. It is a soft, silvery, malleable and ductile metal in the lanthanide group.",
        "appearance": "grayish white",
        "atomicMass": 140.90766,
        "melt": 1208,
        "boil": 3403,
        "density": 6.77,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f3",
        "discoveredBy": "Carl Auer von Welsbach"
    },
    {
        "atomicNumber": 60,
        "symbol": "Nd",
        "name": "Neodymium",
        "category": "lanthanide",
        "group": 3,
        "period": 6,
        "xpos": 6,
        "ypos": 9,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.14,
        "valenceElectrons": 6,
        "summary": "Neodymium is a chemical element with symbol Nd and atomic number 60. It is a soft silvery metal that tarnishes in air.",
        "appearance": "silvery white",
        "atomicMass": 144.242,
        "melt": 1297,
        "boil": 3347,
        "density": 7.01,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f4",
        "discoveredBy": "Carl Auer von Welsbach"
    },
    {
        "atomicNumber": 61,
        "symbol": "Pm",
        "name": "Promethium",
        "category": "lanthanide",
        "group": 3,
        "period": 6,
        "xpos": 7,
        "ypos": 9,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.13,
        "valenceElectrons": 7,
        "summary": "Promethium is a chemical element with the symbol Pm and atomic number 61. All of its isotopes are radioactive.",
        "appearance": "metallic",
        "atomicMass": 145,
        "melt": 1315,
        "boil": 3273,
        "density": 7.26,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f5",
        "discoveredBy": "Chien Shiung Wu"
    },
    {
        "atomicNumber": 62,
        "symbol": "Sm",
        "name": "Samarium",
        "category": "lanthanide",
        "group": 3,
        "period": 6,
        "xpos": 8,
        "ypos": 9,
        "classification": "metal",
        "commonIonCharge": "+3, +2",
        "electronegativity": 1.17,
        "valenceElectrons": 8,
        "summary": "Samarium is a chemical element with symbol Sm and atomic number 62. It is a moderately hard silvery metal that readily oxidizes in air.",
        "appearance": "silvery white",
        "atomicMass": 150.36,
        "melt": 1345,
        "boil": 2173,
        "density": 7.52,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f6",
        "discoveredBy": "Lecoq de Boisbaudran"
    },
    {
        "atomicNumber": 63,
        "symbol": "Eu",
        "name": "Europium",
        "category": "lanthanide",
        "group": 3,
        "period": 6,
        "xpos": 9,
        "ypos": 9,
        "classification": "metal",
        "commonIonCharge": "+3, +2",
        "electronegativity": 1.2,
        "valenceElectrons": 9,
        "summary": "Europium is a chemical element with symbol Eu and atomic number 63. It was isolated in 1901 and is named after the continent of Europe.",
        "appearance": null,
        "atomicMass": 151.964,
        "melt": 1099,
        "boil": 1802,
        "density": 5.264,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f7",
        "discoveredBy": "Eugene-Anatole Demarcay"
    },
    {
        "atomicNumber": 64,
        "symbol": "Gd",
        "name": "Gadolinium",
        "category": "lanthanide",
        "group": 3,
        "period": 6,
        "xpos": 10,
        "ypos": 9,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.2,
        "valenceElectrons": 10,
        "summary": "Gadolinium is a chemical element with symbol Gd and atomic number 64. It is a silvery-white, malleable and ductile rare-earth metal.",
        "appearance": "silvery white",
        "atomicMass": 157.25,
        "melt": 1585,
        "boil": 3273,
        "density": 7.9,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f7 5d1",
        "discoveredBy": "Jean Charles Galissard de Marignac"
    },
    {
        "atomicNumber": 65,
        "symbol": "Tb",
        "name": "Terbium",
        "category": "lanthanide",
        "group": 3,
        "period": 6,
        "xpos": 11,
        "ypos": 9,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.1,
        "valenceElectrons": 11,
        "summary": "Terbium is a chemical element with symbol Tb and atomic number 65. It is a silvery-white rare earth metal that is malleable, ductile and soft.",
        "appearance": "silvery white",
        "atomicMass": 158.92535,
        "melt": 1629,
        "boil": 3396,
        "density": 8.23,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f9",
        "discoveredBy": "Carl Gustaf Mosander"
    },
    {
        "atomicNumber": 66,
        "symbol": "Dy",
        "name": "Dysprosium",
        "category": "lanthanide",
        "group": 3,
        "period": 6,
        "xpos": 12,
        "ypos": 9,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.22,
        "valenceElectrons": 12,
        "summary": "Dysprosium is a chemical element with the symbol Dy and atomic number 66. It is a rare earth element with a metallic silver luster.",
        "appearance": "silvery white",
        "atomicMass": 162.5,
        "melt": 1680,
        "boil": 2840,
        "density": 8.54,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f10",
        "discoveredBy": "Lecoq de Boisbaudran"
    },
    {
        "atomicNumber": 67,
        "symbol": "Ho",
        "name": "Holmium",
        "category": "lanthanide",
        "group": 3,
        "period": 6,
        "xpos": 13,
        "ypos": 9,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.23,
        "valenceElectrons": 13,
        "summary": "Holmium is a chemical element with symbol Ho and atomic number 67. Part of the lanthanide series, holmium is a rare earth element.",
        "appearance": "silvery white",
        "atomicMass": 164.93033,
        "melt": 1734,
        "boil": 2873,
        "density": 8.79,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f11",
        "discoveredBy": "Marc Delafontaine"
    },
    {
        "atomicNumber": 68,
        "symbol": "Er",
        "name": "Erbium",
        "category": "lanthanide",
        "group": 3,
        "period": 6,
        "xpos": 14,
        "ypos": 9,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.24,
        "valenceElectrons": 14,
        "summary": "Erbium is a chemical element in the lanthanide series, with symbol Er and atomic number 68.",
        "appearance": "silvery white",
        "atomicMass": 167.259,
        "melt": 1802,
        "boil": 3141,
        "density": 9.066,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f12",
        "discoveredBy": "Carl Gustaf Mosander"
    },
    {
        "atomicNumber": 69,
        "symbol": "Tm",
        "name": "Thulium",
        "category": "lanthanide",
        "group": 3,
        "period": 6,
        "xpos": 15,
        "ypos": 9,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.25,
        "valenceElectrons": 15,
        "summary": "Thulium is a chemical element with symbol Tm and atomic number 69. It is the thirteenth and antepenultimate element in the lanthanide series.",
        "appearance": "silvery gray",
        "atomicMass": 168.93422,
        "melt": 1818,
        "boil": 2223,
        "density": 9.32,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f13",
        "discoveredBy": "Per Teodor Cleve"
    },
    {
        "atomicNumber": 70,
        "symbol": "Yb",
        "name": "Ytterbium",
        "category": "lanthanide",
        "group": 3,
        "period": 6,
        "xpos": 16,
        "ypos": 9,
        "classification": "metal",
        "commonIonCharge": "+3, +2",
        "electronegativity": 1.1,
        "valenceElectrons": 16,
        "summary": "Ytterbium is a chemical element with symbol Yb and atomic number 70. It is the fourteenth and penultimate element in the lanthanide series.",
        "appearance": null,
        "atomicMass": 173.045,
        "melt": 1097,
        "boil": 1469,
        "density": 6.9,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14",
        "discoveredBy": "Jean Charles Galissard de Marignac"
    },
    {
        "atomicNumber": 71,
        "symbol": "Lu",
        "name": "Lutetium",
        "category": "lanthanide",
        "group": 3,
        "period": 6,
        "xpos": 17,
        "ypos": 9,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.27,
        "valenceElectrons": 3,
        "summary": "Lutetium is a chemical element with symbol Lu and atomic number 71. It is a silvery white metal, which resists corrosion in dry air.",
        "appearance": "silvery white",
        "atomicMass": 174.9668,
        "melt": 1925,
        "boil": 3675,
        "density": 9.841,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d1",
        "discoveredBy": "Georges Urbain"
    },
    {
        "atomicNumber": 72,
        "symbol": "Hf",
        "name": "Hafnium",
        "category": "transition metal",
        "group": 4,
        "period": 6,
        "xpos": 4,
        "ypos": 6,
        "classification": "metal",
        "commonIonCharge": "+4",
        "electronegativity": 1.3,
        "valenceElectrons": 4,
        "summary": "Hafnium is a chemical element with symbol Hf and atomic number 72. A lustrous, silvery gray, tetravalent transition metal.",
        "appearance": "steel gray",
        "atomicMass": 178.49,
        "melt": 2506,
        "boil": 4876,
        "density": 13.31,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d2",
        "discoveredBy": "Dirk Coster"
    },
    {
        "atomicNumber": 73,
        "symbol": "Ta",
        "name": "Tantalum",
        "category": "transition metal",
        "group": 5,
        "period": 6,
        "xpos": 5,
        "ypos": 6,
        "classification": "metal",
        "commonIonCharge": "+5",
        "electronegativity": 1.5,
        "valenceElectrons": 5,
        "summary": "Tantalum is a chemical element with symbol Ta and atomic number 73. A rare, hard, blue-gray, lustrous transition metal.",
        "appearance": "gray blue",
        "atomicMass": 180.94788,
        "melt": 3290,
        "boil": 5731,
        "density": 16.69,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d3",
        "discoveredBy": "Anders Gustaf Ekeberg"
    },
    {
        "atomicNumber": 74,
        "symbol": "W",
        "name": "Tungsten",
        "category": "transition metal",
        "group": 6,
        "period": 6,
        "xpos": 6,
        "ypos": 6,
        "classification": "metal",
        "commonIonCharge": "+6, +4",
        "electronegativity": 2.36,
        "valenceElectrons": 6,
        "summary": "Tungsten, also known as wolfram, is a chemical element with symbol W and atomic number 74.",
        "appearance": "grayish white, lustrous",
        "atomicMass": 183.84,
        "melt": 3695,
        "boil": 6203,
        "density": 19.25,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d4",
        "discoveredBy": "Carl Wilhelm Scheele"
    },
    {
        "atomicNumber": 75,
        "symbol": "Re",
        "name": "Rhenium",
        "category": "transition metal",
        "group": 7,
        "period": 6,
        "xpos": 7,
        "ypos": 6,
        "classification": "metal",
        "commonIonCharge": "+7, +4",
        "electronegativity": 1.9,
        "valenceElectrons": 7,
        "summary": "Rhenium is a chemical element with symbol Re and atomic number 75. It is a silvery-white, heavy, third-row transition metal.",
        "appearance": "grayish white",
        "atomicMass": 186.207,
        "melt": 3459,
        "boil": 5903,
        "density": 21.02,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d5",
        "discoveredBy": "Masataka Ogawa"
    },
    {
        "atomicNumber": 76,
        "symbol": "Os",
        "name": "Osmium",
        "category": "transition metal",
        "group": 8,
        "period": 6,
        "xpos": 8,
        "ypos": 6,
        "classification": "metal",
        "commonIonCharge": "+4, +3",
        "electronegativity": 2.2,
        "valenceElectrons": 8,
        "summary": "Osmium is a chemical element with symbol Os and atomic number 76. It is the densest naturally occurring element.",
        "appearance": "silvery, blue cast",
        "atomicMass": 190.23,
        "melt": 3306,
        "boil": 5285,
        "density": 22.59,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d6",
        "discoveredBy": "Smithson Tennant"
    },
    {
        "atomicNumber": 77,
        "symbol": "Ir",
        "name": "Iridium",
        "category": "transition metal",
        "group": 9,
        "period": 6,
        "xpos": 9,
        "ypos": 6,
        "classification": "metal",
        "commonIonCharge": "+3, +4",
        "electronegativity": 2.2,
        "valenceElectrons": 9,
        "summary": "Iridium is a chemical element with symbol Ir and atomic number 77. A very hard, brittle, silvery-white transition metal of the platinum group.",
        "appearance": "silvery white",
        "atomicMass": 192.217,
        "melt": 2719,
        "boil": 4403,
        "density": 22.56,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d7",
        "discoveredBy": "Smithson Tennant"
    },
    {
        "atomicNumber": 78,
        "symbol": "Pt",
        "name": "Platinum",
        "category": "transition metal",
        "group": 10,
        "period": 6,
        "xpos": 10,
        "ypos": 6,
        "classification": "metal",
        "commonIonCharge": "+2, +4",
        "electronegativity": 2.28,
        "valenceElectrons": 10,
        "summary": "Platinum is a chemical element with symbol Pt and atomic number 78. It is a dense, malleable, ductile, highly unreactive, precious, gray-white transition metal.",
        "appearance": "silvery white",
        "atomicMass": 195.084,
        "melt": 2041.4,
        "boil": 4098,
        "density": 21.45,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s1 4f14 5d9",
        "discoveredBy": "Antonio de Ulloa"
    },
    {
        "atomicNumber": 79,
        "symbol": "Au",
        "name": "Gold",
        "category": "transition metal",
        "group": 11,
        "period": 6,
        "xpos": 11,
        "ypos": 6,
        "classification": "metal",
        "commonIonCharge": "+1, +3",
        "electronegativity": 2.54,
        "valenceElectrons": 11,
        "summary": "Gold is a chemical element with symbol Au and atomic number 79. In its purest form, it is a bright, slightly reddish yellow, dense, soft, malleable and ductile metal.",
        "appearance": "metallic yellow",
        "atomicMass": 196.966569,
        "melt": 1337.33,
        "boil": 3243,
        "density": 19.3,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s1 4f14 5d10",
        "discoveredBy": "Ancient"
    },
    {
        "atomicNumber": 80,
        "symbol": "Hg",
        "name": "Mercury",
        "category": "transition metal",
        "group": 12,
        "period": 6,
        "xpos": 12,
        "ypos": 6,
        "classification": "metal",
        "commonIonCharge": "+1, +2",
        "electronegativity": 2.0,
        "valenceElectrons": 2,
        "summary": "Mercury is a chemical element with symbol Hg and atomic number 80. It is the only metallic element that is liquid at standard conditions.",
        "appearance": "silvery",
        "atomicMass": 200.592,
        "melt": 234.321,
        "boil": 629.88,
        "density": 13.534,
        "phase": "Liquid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10",
        "discoveredBy": "Ancient"
    },
    {
        "atomicNumber": 81,
        "symbol": "Tl",
        "name": "Thallium",
        "category": "post-transition metal",
        "group": 13,
        "period": 6,
        "xpos": 13,
        "ypos": 6,
        "classification": "metal",
        "commonIonCharge": "+1, +3",
        "electronegativity": 1.62,
        "valenceElectrons": 3,
        "summary": "Thallium is a chemical element with symbol Tl and atomic number 81. This soft gray post-transition metal is not found free in nature.",
        "appearance": "silvery white",
        "atomicMass": 204.38,
        "melt": 577,
        "boil": 1746,
        "density": 11.85,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p1",
        "discoveredBy": "William Crookes"
    },
    {
        "atomicNumber": 82,
        "symbol": "Pb",
        "name": "Lead",
        "category": "post-transition metal",
        "group": 14,
        "period": 6,
        "xpos": 14,
        "ypos": 6,
        "classification": "metal",
        "commonIonCharge": "+2, +4",
        "electronegativity": 1.87,
        "valenceElectrons": 4,
        "summary": "Lead is a chemical element with symbol Pb and atomic number 82. It is a heavy metal that is denser than most common materials.",
        "appearance": "metallic gray",
        "atomicMass": 207.2,
        "melt": 600.61,
        "boil": 2022,
        "density": 11.34,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p2",
        "discoveredBy": "Ancient"
    },
    {
        "atomicNumber": 83,
        "symbol": "Bi",
        "name": "Bismuth",
        "category": "post-transition metal",
        "group": 15,
        "period": 6,
        "xpos": 15,
        "ypos": 6,
        "classification": "metal",
        "commonIonCharge": "+3, +5",
        "electronegativity": 2.02,
        "valenceElectrons": 5,
        "summary": "Bismuth is a chemical element with symbol Bi and atomic number 83. Bismuth is a brittle metal with a white, silver-pink hue.",
        "appearance": "lustrous silver",
        "atomicMass": 208.9804,
        "melt": 544.7,
        "boil": 1837,
        "density": 9.78,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p3",
        "discoveredBy": "Claude Francois Geoffroy"
    },
    {
        "atomicNumber": 84,
        "symbol": "Po",
        "name": "Polonium",
        "category": "metalloid",
        "group": 16,
        "period": 6,
        "xpos": 16,
        "ypos": 6,
        "classification": "metalloid",
        "commonIonCharge": "+2, +4",
        "electronegativity": 2.0,
        "valenceElectrons": 6,
        "summary": "Polonium is a chemical element with symbol Po and atomic number 84. A rare and highly radioactive element with no stable isotopes.",
        "appearance": "silvery",
        "atomicMass": 209,
        "melt": 527,
        "boil": 1235,
        "density": 9.196,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p4",
        "discoveredBy": "Pierre Curie"
    },
    {
        "atomicNumber": 85,
        "symbol": "At",
        "name": "Astatine",
        "category": "metalloid",
        "group": 17,
        "period": 6,
        "xpos": 17,
        "ypos": 6,
        "classification": "metalloid",
        "commonIonCharge": "-1, +1",
        "electronegativity": 2.2,
        "valenceElectrons": 7,
        "summary": "Astatine is a radioactive chemical element with symbol At and atomic number 85. It is the rarest naturally occurring element in the Earth's crust.",
        "appearance": "unknown, probably metallic",
        "atomicMass": 210,
        "melt": 575,
        "boil": 610,
        "density": 6.35,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p5",
        "discoveredBy": "Dale R. Corson"
    },
    {
        "atomicNumber": 86,
        "symbol": "Rn",
        "name": "Radon",
        "category": "noble gas",
        "group": 18,
        "period": 6,
        "xpos": 18,
        "ypos": 6,
        "classification": "nonmetal",
        "commonIonCharge": null,
        "electronegativity": 2.2,
        "valenceElectrons": 8,
        "summary": "Radon is a chemical element with symbol Rn and atomic number 86. It is a radioactive, colorless, odorless, tasteless noble gas.",
        "appearance": "colorless gas, occasionally glows green or red",
        "atomicMass": 222,
        "melt": 202,
        "boil": 211.5,
        "density": 9.73,
        "phase": "Gas",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6",
        "discoveredBy": "Friedrich Ernst Dorn"
    },
    {
        "atomicNumber": 87,
        "symbol": "Fr",
        "name": "Francium",
        "category": "alkali metal",
        "group": 1,
        "period": 7,
        "xpos": 1,
        "ypos": 7,
        "classification": "metal",
        "commonIonCharge": "+1",
        "electronegativity": 0.79,
        "valenceElectrons": 1,
        "summary": "Francium is a chemical element with symbol Fr and atomic number 87. It was formerly known as eka-caesium.",
        "appearance": null,
        "atomicMass": 223,
        "melt": 300,
        "boil": 950,
        "density": 1.87,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s1",
        "discoveredBy": "Marguerite Perey"
    },
    {
        "atomicNumber": 88,
        "symbol": "Ra",
        "name": "Radium",
        "category": "alkaline earth metal",
        "group": 2,
        "period": 7,
        "xpos": 2,
        "ypos": 7,
        "classification": "metal",
        "commonIonCharge": "+2",
        "electronegativity": 0.9,
        "valenceElectrons": 2,
        "summary": "Radium is a chemical element with symbol Ra and atomic number 88. It is the sixth element in group 2 of the periodic table, also known as the alkaline earth metals.",
        "appearance": "silvery white metallic",
        "atomicMass": 226,
        "melt": 973,
        "boil": 2010,
        "density": 5.5,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2",
        "discoveredBy": "Pierre Curie"
    },
    {
        "atomicNumber": 89,
        "symbol": "Ac",
        "name": "Actinium",
        "category": "actinide",
        "group": 3,
        "period": 7,
        "xpos": 3,
        "ypos": 10,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.1,
        "valenceElectrons": 3,
        "summary": "Actinium is a radioactive chemical element with symbol Ac and atomic number 89.",
        "appearance": null,
        "atomicMass": 227,
        "melt": 1323,
        "boil": 3473,
        "density": 10.07,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 6d1",
        "discoveredBy": "Friedrich Oskar Giesel"
    },
    {
        "atomicNumber": 90,
        "symbol": "Th",
        "name": "Thorium",
        "category": "actinide",
        "group": 3,
        "period": 7,
        "xpos": 4,
        "ypos": 10,
        "classification": "metal",
        "commonIonCharge": "+4",
        "electronegativity": 1.3,
        "valenceElectrons": 4,
        "summary": "Thorium is a chemical element with symbol Th and atomic number 90. A radioactive actinide metal.",
        "appearance": "silvery, often with black tarnish",
        "atomicMass": 232.0377,
        "melt": 2023,
        "boil": 5061,
        "density": 11.724,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 6d2",
        "discoveredBy": "Jons Jacob Berzelius"
    },
    {
        "atomicNumber": 91,
        "symbol": "Pa",
        "name": "Protactinium",
        "category": "actinide",
        "group": 3,
        "period": 7,
        "xpos": 5,
        "ypos": 10,
        "classification": "metal",
        "commonIonCharge": "+5, +4",
        "electronegativity": 1.5,
        "valenceElectrons": 5,
        "summary": "Protactinium is a chemical element with symbol Pa and atomic number 91.",
        "appearance": "bright, silvery metallic luster",
        "atomicMass": 231.03588,
        "melt": 1841,
        "boil": 4300,
        "density": 15.37,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f2 6d1",
        "discoveredBy": "William Crookes"
    },
    {
        "atomicNumber": 92,
        "symbol": "U",
        "name": "Uranium",
        "category": "actinide",
        "group": 3,
        "period": 7,
        "xpos": 6,
        "ypos": 10,
        "classification": "metal",
        "commonIonCharge": "+6, +4",
        "electronegativity": 1.38,
        "valenceElectrons": 6,
        "summary": "Uranium is a chemical element with symbol U and atomic number 92. It is a silvery-white metal in the actinide series of the periodic table.",
        "appearance": null,
        "atomicMass": 238.02891,
        "melt": 1405.3,
        "boil": 4404,
        "density": 19.1,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f3 6d1",
        "discoveredBy": "Martin Heinrich Klaproth"
    },
    {
        "atomicNumber": 93,
        "symbol": "Np",
        "name": "Neptunium",
        "category": "actinide",
        "group": 3,
        "period": 7,
        "xpos": 7,
        "ypos": 10,
        "classification": "metal",
        "commonIonCharge": "+5, +4, +3",
        "electronegativity": 1.36,
        "valenceElectrons": 7,
        "summary": "Neptunium is a chemical element with symbol Np and atomic number 93. A radioactive actinide metal.",
        "appearance": "silvery metallic",
        "atomicMass": 237,
        "melt": 912,
        "boil": 4447,
        "density": 20.45,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f4 6d1",
        "discoveredBy": "Edwin McMillan"
    },
    {
        "atomicNumber": 94,
        "symbol": "Pu",
        "name": "Plutonium",
        "category": "actinide",
        "group": 3,
        "period": 7,
        "xpos": 8,
        "ypos": 10,
        "classification": "metal",
        "commonIonCharge": "+4, +6",
        "electronegativity": 1.28,
        "valenceElectrons": 8,
        "summary": "Plutonium is a transuranic radioactive chemical element with symbol Pu and atomic number 94.",
        "appearance": "silvery white, tarnishing to dark gray in air",
        "atomicMass": 244,
        "melt": 912.5,
        "boil": 3505,
        "density": 19.816,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f6",
        "discoveredBy": "Glenn T. Seaborg"
    },
    {
        "atomicNumber": 95,
        "symbol": "Am",
        "name": "Americium",
        "category": "actinide",
        "group": 3,
        "period": 7,
        "xpos": 9,
        "ypos": 10,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.3,
        "valenceElectrons": 9,
        "summary": "Americium is a radioactive transuranic chemical element with symbol Am and atomic number 95.",
        "appearance": "silvery white",
        "atomicMass": 243,
        "melt": 1449,
        "boil": 2880,
        "density": 12,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f7",
        "discoveredBy": "Glenn T. Seaborg"
    },
    {
        "atomicNumber": 96,
        "symbol": "Cm",
        "name": "Curium",
        "category": "actinide",
        "group": 3,
        "period": 7,
        "xpos": 10,
        "ypos": 10,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.3,
        "valenceElectrons": 10,
        "summary": "Curium is a transuranic radioactive chemical element with symbol Cm and atomic number 96.",
        "appearance": "silvery metallic",
        "atomicMass": 247,
        "melt": 1613,
        "boil": 3383,
        "density": 13.51,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f7 6d1",
        "discoveredBy": "Glenn T. Seaborg"
    },
    {
        "atomicNumber": 97,
        "symbol": "Bk",
        "name": "Berkelium",
        "category": "actinide",
        "group": 3,
        "period": 7,
        "xpos": 11,
        "ypos": 10,
        "classification": "metal",
        "commonIonCharge": "+3, +4",
        "electronegativity": 1.3,
        "valenceElectrons": 11,
        "summary": "Berkelium is a transuranic radioactive chemical element with symbol Bk and atomic number 97.",
        "appearance": "silvery",
        "atomicMass": 247,
        "melt": 1259,
        "boil": 2900,
        "density": 14.78,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f9",
        "discoveredBy": "Lawrence Berkeley National Laboratory"
    },
    {
        "atomicNumber": 98,
        "symbol": "Cf",
        "name": "Californium",
        "category": "actinide",
        "group": 3,
        "period": 7,
        "xpos": 12,
        "ypos": 10,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.3,
        "valenceElectrons": 12,
        "summary": "Californium is a radioactive metallic chemical element with symbol Cf and atomic number 98.",
        "appearance": "silvery",
        "atomicMass": 251,
        "melt": 1173,
        "boil": 1743,
        "density": 15.1,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f10",
        "discoveredBy": "Lawrence Berkeley National Laboratory"
    },
    {
        "atomicNumber": 99,
        "symbol": "Es",
        "name": "Einsteinium",
        "category": "actinide",
        "group": 3,
        "period": 7,
        "xpos": 13,
        "ypos": 10,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.3,
        "valenceElectrons": 13,
        "summary": "Einsteinium is a synthetic element with symbol Es and atomic number 99.",
        "appearance": "silver-colored",
        "atomicMass": 252,
        "melt": 1133,
        "boil": 1269,
        "density": 8.84,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f11",
        "discoveredBy": "Lawrence Berkeley National Laboratory"
    },
    {
        "atomicNumber": 100,
        "symbol": "Fm",
        "name": "Fermium",
        "category": "actinide",
        "group": 3,
        "period": 7,
        "xpos": 14,
        "ypos": 10,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.3,
        "valenceElectrons": 14,
        "summary": "Fermium is a synthetic element with symbol Fm and atomic number 100.",
        "appearance": null,
        "atomicMass": 257,
        "melt": 1800,
        "boil": null,
        "density": null,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f12",
        "discoveredBy": "Lawrence Berkeley National Laboratory"
    },
    {
        "atomicNumber": 101,
        "symbol": "Md",
        "name": "Mendelevium",
        "category": "actinide",
        "group": 3,
        "period": 7,
        "xpos": 15,
        "ypos": 10,
        "classification": "metal",
        "commonIonCharge": "+3, +2",
        "electronegativity": 1.3,
        "valenceElectrons": 15,
        "summary": "Mendelevium is a synthetic element with symbol Md and atomic number 101.",
        "appearance": null,
        "atomicMass": 258,
        "melt": 1100,
        "boil": null,
        "density": null,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f13",
        "discoveredBy": "Lawrence Berkeley National Laboratory"
    },
    {
        "atomicNumber": 102,
        "symbol": "No",
        "name": "Nobelium",
        "category": "actinide",
        "group": 3,
        "period": 7,
        "xpos": 16,
        "ypos": 10,
        "classification": "metal",
        "commonIonCharge": "+2, +3",
        "electronegativity": 1.3,
        "valenceElectrons": 16,
        "summary": "Nobelium is a synthetic chemical element with symbol No and atomic number 102.",
        "appearance": null,
        "atomicMass": 259,
        "melt": 1100,
        "boil": null,
        "density": null,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14",
        "discoveredBy": "Joint Institute for Nuclear Research"
    },
    {
        "atomicNumber": 103,
        "symbol": "Lr",
        "name": "Lawrencium",
        "category": "actinide",
        "group": 3,
        "period": 7,
        "xpos": 17,
        "ypos": 10,
        "classification": "metal",
        "commonIonCharge": "+3",
        "electronegativity": 1.3,
        "valenceElectrons": 3,
        "summary": "Lawrencium is a synthetic chemical element with symbol Lr and atomic number 103.",
        "appearance": null,
        "atomicMass": 266,
        "melt": 1900,
        "boil": null,
        "density": null,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 7p1",
        "discoveredBy": "Lawrence Berkeley National Laboratory"
    },
    {
        "atomicNumber": 104,
        "symbol": "Rf",
        "name": "Rutherfordium",
        "category": "transition metal",
        "group": 4,
        "period": 7,
        "xpos": 4,
        "ypos": 7,
        "classification": "metal",
        "commonIonCharge": "+4",
        "electronegativity": null,
        "valenceElectrons": 4,
        "summary": "Rutherfordium is a chemical element with symbol Rf and atomic number 104.",
        "appearance": null,
        "atomicMass": 267,
        "melt": 2400,
        "boil": 5800,
        "density": 23.2,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d2",
        "discoveredBy": "Joint Institute for Nuclear Research"
    },
    {
        "atomicNumber": 105,
        "symbol": "Db",
        "name": "Dubnium",
        "category": "transition metal",
        "group": 5,
        "period": 7,
        "xpos": 5,
        "ypos": 7,
        "classification": "metal",
        "commonIonCharge": "+5",
        "electronegativity": null,
        "valenceElectrons": 5,
        "summary": "Dubnium is a chemical element with symbol Db and atomic number 105.",
        "appearance": null,
        "atomicMass": 268,
        "melt": null,
        "boil": null,
        "density": 29.3,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d3",
        "discoveredBy": "Joint Institute for Nuclear Research"
    },
    {
        "atomicNumber": 106,
        "symbol": "Sg",
        "name": "Seaborgium",
        "category": "transition metal",
        "group": 6,
        "period": 7,
        "xpos": 6,
        "ypos": 7,
        "classification": "metal",
        "commonIonCharge": "+6",
        "electronegativity": null,
        "valenceElectrons": 6,
        "summary": "Seaborgium is a synthetic element with symbol Sg and atomic number 106.",
        "appearance": null,
        "atomicMass": 269,
        "melt": null,
        "boil": null,
        "density": 35.0,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d4",
        "discoveredBy": "Lawrence Berkeley National Laboratory"
    },
    {
        "atomicNumber": 107,
        "symbol": "Bh",
        "name": "Bohrium",
        "category": "transition metal",
        "group": 7,
        "period": 7,
        "xpos": 7,
        "ypos": 7,
        "classification": "metal",
        "commonIonCharge": "+7",
        "electronegativity": null,
        "valenceElectrons": 7,
        "summary": "Bohrium is a chemical element with symbol Bh and atomic number 107.",
        "appearance": null,
        "atomicMass": 270,
        "melt": null,
        "boil": null,
        "density": 37.1,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d5",
        "discoveredBy": "Gesellschaft fur Schwerionenforschung"
    },
    {
        "atomicNumber": 108,
        "symbol": "Hs",
        "name": "Hassium",
        "category": "transition metal",
        "group": 8,
        "period": 7,
        "xpos": 8,
        "ypos": 7,
        "classification": "metal",
        "commonIonCharge": "+8",
        "electronegativity": null,
        "valenceElectrons": 8,
        "summary": "Hassium is a chemical element with symbol Hs and atomic number 108.",
        "appearance": null,
        "atomicMass": 269,
        "melt": 126,
        "boil": null,
        "density": 40.7,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d6",
        "discoveredBy": "Gesellschaft fur Schwerionenforschung"
    },
    {
        "atomicNumber": 109,
        "symbol": "Mt",
        "name": "Meitnerium",
        "category": "unknown",
        "group": 9,
        "period": 7,
        "xpos": 9,
        "ypos": 7,
        "classification": "metal",
        "commonIonCharge": null,
        "electronegativity": null,
        "valenceElectrons": 9,
        "summary": "Meitnerium is a synthetic element with symbol Mt and atomic number 109.",
        "appearance": null,
        "atomicMass": 278,
        "melt": null,
        "boil": null,
        "density": 37.4,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d7",
        "discoveredBy": "Gesellschaft fur Schwerionenforschung"
    },
    {
        "atomicNumber": 110,
        "symbol": "Ds",
        "name": "Darmstadtium",
        "category": "unknown",
        "group": 10,
        "period": 7,
        "xpos": 10,
        "ypos": 7,
        "classification": "metal",
        "commonIonCharge": null,
        "electronegativity": null,
        "valenceElectrons": 10,
        "summary": "Darmstadtium is a chemical element with symbol Ds and atomic number 110.",
        "appearance": null,
        "atomicMass": 281,
        "melt": null,
        "boil": null,
        "density": 34.8,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d8",
        "discoveredBy": "Gesellschaft fur Schwerionenforschung"
    },
    {
        "atomicNumber": 111,
        "symbol": "Rg",
        "name": "Roentgenium",
        "category": "unknown",
        "group": 11,
        "period": 7,
        "xpos": 11,
        "ypos": 7,
        "classification": "metal",
        "commonIonCharge": null,
        "electronegativity": null,
        "valenceElectrons": 11,
        "summary": "Roentgenium is a chemical element with symbol Rg and atomic number 111.",
        "appearance": null,
        "atomicMass": 282,
        "melt": null,
        "boil": null,
        "density": 28.7,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d9",
        "discoveredBy": "Gesellschaft fur Schwerionenforschung"
    },
    {
        "atomicNumber": 112,
        "symbol": "Cn",
        "name": "Copernicium",
        "category": "transition metal",
        "group": 12,
        "period": 7,
        "xpos": 12,
        "ypos": 7,
        "classification": "metal",
        "commonIonCharge": "+2",
        "electronegativity": null,
        "valenceElectrons": 2,
        "summary": "Copernicium is a chemical element with symbol Cn and atomic number 112.",
        "appearance": null,
        "atomicMass": 285,
        "melt": null,
        "boil": 3570,
        "density": 14.0,
        "phase": "Liquid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10",
        "discoveredBy": "Gesellschaft fur Schwerionenforschung"
    },
    {
        "atomicNumber": 113,
        "symbol": "Nh",
        "name": "Nihonium",
        "category": "unknown",
        "group": 13,
        "period": 7,
        "xpos": 13,
        "ypos": 7,
        "classification": "metal",
        "commonIonCharge": null,
        "electronegativity": null,
        "valenceElectrons": 3,
        "summary": "Nihonium is a synthetic element with symbol Nh and atomic number 113.",
        "appearance": null,
        "atomicMass": 286,
        "melt": 700,
        "boil": 1430,
        "density": 16,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p1",
        "discoveredBy": "RIKEN"
    },
    {
        "atomicNumber": 114,
        "symbol": "Fl",
        "name": "Flerovium",
        "category": "post-transition metal",
        "group": 14,
        "period": 7,
        "xpos": 14,
        "ypos": 7,
        "classification": "metal",
        "commonIonCharge": null,
        "electronegativity": null,
        "valenceElectrons": 4,
        "summary": "Flerovium is a superheavy artificial chemical element with symbol Fl and atomic number 114.",
        "appearance": null,
        "atomicMass": 289,
        "melt": 340,
        "boil": 420,
        "density": 14,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p2",
        "discoveredBy": "Joint Institute for Nuclear Research"
    },
    {
        "atomicNumber": 115,
        "symbol": "Mc",
        "name": "Moscovium",
        "category": "unknown",
        "group": 15,
        "period": 7,
        "xpos": 15,
        "ypos": 7,
        "classification": "metal",
        "commonIonCharge": null,
        "electronegativity": null,
        "valenceElectrons": 5,
        "summary": "Moscovium is a synthetic superheavy element with symbol Mc and atomic number 115.",
        "appearance": null,
        "atomicMass": 289,
        "melt": 670,
        "boil": 1400,
        "density": 13.5,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p3",
        "discoveredBy": "Joint Institute for Nuclear Research"
    },
    {
        "atomicNumber": 116,
        "symbol": "Lv",
        "name": "Livermorium",
        "category": "unknown",
        "group": 16,
        "period": 7,
        "xpos": 16,
        "ypos": 7,
        "classification": "metal",
        "commonIonCharge": null,
        "electronegativity": null,
        "valenceElectrons": 6,
        "summary": "Livermorium is a synthetic superheavy element with symbol Lv and atomic number 116.",
        "appearance": null,
        "atomicMass": 293,
        "melt": 709,
        "boil": 1085,
        "density": 12.9,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p4",
        "discoveredBy": "Joint Institute for Nuclear Research"
    },
    {
        "atomicNumber": 117,
        "symbol": "Ts",
        "name": "Tennessine",
        "category": "unknown",
        "group": 17,
        "period": 7,
        "xpos": 17,
        "ypos": 7,
        "classification": "metalloid",
        "commonIonCharge": null,
        "electronegativity": null,
        "valenceElectrons": 7,
        "summary": "Tennessine is a superheavy artificial chemical element with atomic number 117 and symbol Ts.",
        "appearance": null,
        "atomicMass": 294,
        "melt": 723,
        "boil": 883,
        "density": 7.17,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p5",
        "discoveredBy": "Joint Institute for Nuclear Research"
    },
    {
        "atomicNumber": 118,
        "symbol": "Og",
        "name": "Oganesson",
        "category": "unknown",
        "group": 18,
        "period": 7,
        "xpos": 18,
        "ypos": 7,
        "classification": "nonmetal",
        "commonIonCharge": null,
        "electronegativity": null,
        "valenceElectrons": 8,
        "summary": "Oganesson is a transactinide element with atomic number 118 and symbol Og.",
        "appearance": null,
        "atomicMass": 294,
        "melt": null,
        "boil": 350,
        "density": 4.95,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p6",
        "discoveredBy": "Joint Institute for Nuclear Research"
    },
    {
        "atomicNumber": 119,
        "symbol": "Uue",
        "name": "Ununennium",
        "category": "unknown",
        "group": 1,
        "period": 8,
        "xpos": 1,
        "ypos": 8,
        "classification": "metal",
        "commonIonCharge": "+1",
        "electronegativity": null,
        "valenceElectrons": 1,
        "summary": "Ununennium is the hypothetical chemical element with symbol Uue and atomic number 119.",
        "appearance": null,
        "atomicMass": 315,
        "melt": null,
        "boil": 630,
        "density": 3,
        "phase": "Solid",
        "electronConfiguration": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p6 8s1",
        "discoveredBy": "GSI Helmholtz Centre for Heavy Ion Research"
    }
];
